info:
  app:
    name: eureka:peer2
    version: v1.0
spring:
  application:
    name: eureka
# actuator 是否需要安全认证
management:
  security:
    enabled: false
server:
  port: 2222
eureka:
  instance:
    #实例的主机名
    hostname: peer2
    # 是否加载IP
    prefer-ip-address: true
    # 手动设置IP
    instance-id: 172.16.43.11:${server.port}
  client:
    #设置是否向注册中心注册，默认是true
    register-with-eureka: true
    #是否需要去检索寻找服务，默认是true
    fetch-registry: true
    service-url:
    #指定注册中心
      defaultZone: http://cheng:123@peer1:1111/eureka/
