info:
  app:
    name: cheng
    version: v1.0
# actuator 是否需要安全认证
management:
  security:
    enabled: false


# 安全认证的配置
security:
  basic:
    enabled: false
  user:
    name:  cheng  # 用户名
    password: 123   # 用户密码


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#热加载
spring:
  devtools:
    restart:
      enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**

