spring:
  application:
    name: eureka
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:2222/eureka/


